// Match Equity Table — loader and lookup.
//
// Indexed as met.met[a][b] where a is us-away (points we still need to
// win the match) and b is them-away. Boundary: a=0 -> we won (MWC=1),
// b=0 -> they won (MWC=0). Generated by training/met_build.py.

export interface Met {
  version: number;
  model: string;        // "dead-cube" for the v1 table
  matches: number;      // largest score supported (clamped at lookup)
  p_w: number;          // assumed cubeless win prob (symmetric: 0.5)
  gammon_rate: number;  // fraction of wins that are gammons-or-better
  backgammon_rate: number;
  cube_efficiency: number; // τ, consumed by the cube decision module
  met: number[][];      // met[a][b], shape (matches+1) × (matches+1)
}

export function parseMet(raw: unknown): Met {
  if (!raw || typeof raw !== "object") throw new Error("met: not an object");
  const r = raw as Record<string, unknown>;
  const matches = Number(r.matches);
  if (!Number.isFinite(matches) || matches < 1) {
    throw new Error(`met: invalid matches: ${r.matches}`);
  }
  const met = r.met;
  if (!Array.isArray(met) || met.length !== matches + 1) {
    throw new Error(`met: expected met to be a (matches+1)-length array`);
  }
  for (let a = 0; a <= matches; a++) {
    const row = met[a];
    if (!Array.isArray(row) || row.length !== matches + 1) {
      throw new Error(`met: row ${a} has wrong length`);
    }
    for (let b = 0; b <= matches; b++) {
      if (typeof row[b] !== "number" || !Number.isFinite(row[b])) {
        throw new Error(`met: met[${a}][${b}] not finite`);
      }
    }
  }
  return {
    version: Number(r.version ?? 1),
    model: String(r.model ?? "dead-cube"),
    matches,
    p_w: Number(r.p_w ?? 0.5),
    gammon_rate: Number(r.gammon_rate ?? 0.26),
    backgammon_rate: Number(r.backgammon_rate ?? 0.01),
    cube_efficiency: Number(r.cube_efficiency ?? 0.7),
    met: met as number[][],
  };
}

export async function loadMet(url: string): Promise<Met> {
  const r = await fetch(url);
  if (!r.ok) throw new Error(`met: fetch ${url} -> ${r.status}`);
  return parseMet(await r.json());
}

// Look up MWC for us at score (awayUs, awayThem). Scores are clamped to
// [0, matches]; awayUs===0 -> MWC=1 (we already won), awayThem===0 -> MWC=0.
export function metEntry(met: Met, awayUs: number, awayThem: number): number {
  const N = met.matches;
  const a = Math.max(0, Math.min(N, Math.round(awayUs)));
  const b = Math.max(0, Math.min(N, Math.round(awayThem)));
  if (a === 0) return 1.0;
  if (b === 0) return 0.0;
  return met.met[a][b];
}
